

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build: .
    container_name: nodejs-app
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    command: node index.js

  consumer:
    build: .
    container_name: order-consumer
    depends_on:
      - rabbitmq
    command: node queueConsumer.js  